### ISSUE TITLE
I have tried to download the foot print but got this error

### ISSUE THREAD

**Issue by arslan437** [yaqwsx/EasyEDAFootprintScraper#6]
here is the error detail

```
& 'C:\Program Files\KiCad\7.0\bin\python.exe' ./fetchComponent.py fetchlcsc --kicadLib test.pretty --force C558438
Traceback (most recent call last):
  File "C:\Users\Arslan\Documents\KiCad\7.0\scripting\plugins\EasyEDAFootprintScraper\fetchComponent.py", line 264, in <module>
    cli()
  File "C:\Users\Arslan\Documents\KiCad\7.0\3rdparty\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Arslan\Documents\KiCad\7.0\3rdparty\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Arslan\Documents\KiCad\7.0\3rdparty\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Arslan\Documents\KiCad\7.0\3rdparty\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Arslan\Documents\KiCad\7.0\3rdparty\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Arslan\Documents\KiCad\7.0\scripting\plugins\EasyEDAFootprintScraper\fetchComponent.py", line 234, in fetchLcsc
    componentDetail, footprint = fetchAndConvert(cinfo, token, cookies)
  File "C:\Users\Arslan\Documents\KiCad\7.0\scripting\plugins\EasyEDAFootprintScraper\fetchComponent.py", line 166, in fetchAndConvert
    kicadBoard = easyEdaToKicad(packageBoard)
  File "C:\Users\Arslan\Documents\KiCad\7.0\scripting\plugins\EasyEDAFootprintScraper\fetchComponent.py", line 115, in easyEdaToKicad
    subprocess.check_call(["easyeda2kicad", easyFilename, kicadFilename])
  File "C:\Program Files\KiCad\7.0\bin\Lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\KiCad\7.0\bin\Lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\KiCad\7.0\bin\Lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\KiCad\7.0\bin\Lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by yaqwsx** [comment]
You miss https://github.com/wokwi/easyeda2kicad installed. And even then, it is probable that the tool won't work - it wasn't updated for a while and it is possible that JLC PCB and EasyEDA changed their API.

**Comment by arslan437** [comment]
Where I need to run this command.

```
npm install -g easyeda2kicad
```
