### ISSUE TITLE
TypeError: in method 'EDA_ITEM_SetPosition'

### ISSUE THREAD

**Issue by MartinVerges** [yaqwsx/EasyEDAFootprintScraper#7]
Hello,

thanks for your work. Unfortunately it seems to not work for me.

```
~/test$ ./fetchComponent.py fetchlcsc --kicadLib test.pretty --force C393941
Warning: unsupported layer id: 101
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 99
Warning: unsupported shape SVGNODE in footprint 
Traceback (most recent call last):
  File "/home/martin/test/./fetchComponent.py", line 264, in <module>
    cli()
  File "/home/martin/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/martin/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/martin/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/martin/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/martin/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/martin/test/./fetchComponent.py", line 234, in fetchLcsc
    componentDetail, footprint = fetchAndConvert(cinfo, token, cookies)
  File "/home/martin/test/./fetchComponent.py", line 168, in fetchAndConvert
    postProcessFootprint(footprint)
  File "/home/martin/test/./fetchComponent.py", line 151, in postProcessFootprint
    footprint.Reference().SetPosition(refPos)
  File "/usr/lib/python3/dist-packages/pcbnew.py", line 1779, in SetPosition
    return _pcbnew.EDA_ITEM_SetPosition(self, aPos)
TypeError: in method 'EDA_ITEM_SetPosition', argument 2 of type 'VECTOR2I const &'
```

Im using kicad 7.0.1
```
~/test$ dpkg -l |grep kicad
ii  kicad                                    7.0.1-0-202303150329+3b83917a11~172~ubuntu22.10.1 amd64        Electronic schematic and PCB design software
``` 

Having easyeda2kicad 1.9.5 (should be latest):
```
~/test$ npm list -g --depth 0|grep easy
├── easyeda2kicad@1.9.5
```

Any clue how to fix that?

**Comment by yaqwsx** [comment]
KiCAD 7 is not (yet) supported.

**Comment by MartinVerges** [comment]
Good to know, thank you!

**Comment by WardBenjamin** [comment]
With #10 applied (a very simple patch), this works with KiCad 7.
